variable "PROJECT_ID" {}
variable "default_region" {}
variable "default_zone" {}
variable "template_name" {}
variable "tag" {}
variable "label" {}
variable "machine_type" {}
variable "network" {}
variable "email" {}
variable "disk_size" {}
variable "disk_type" {}